#!/bin/bash
ipfs init
nohup ipfs daemon &

sleep 10

ipfs id

sleep 10

# Add any existing data. Help speed up startup.
nohup ipfs add -r /home/safeuser/koa-ipfs-blog/ipfs-data &

sleep 5

# Copy the config file.
cp /home/safeuser/.ipfs/common.js /home/safeuser/koa-ipfs-blog/config/env/

export KOA_ENV=production
npm start
